name: Deploy to aaPanel

on:
  push:
    branches:
      - main

  # Allow manual trigger for testing
  workflow_dispatch:

env:
  # Tên dự án trên aaPanel (thường là domain)
  AAPANEL_PROJECT_NAME: "mln131.aizy.io.vn"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy deploy script to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT || '22' }}
          source: "scripts/deploy.sh"
          target: "/tmp"
          strip_components: 1

      - name: Execute deploy script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT || '22' }}
          script: |
            echo "Checking deployment script..."
            chmod +x /tmp/deploy.sh
            
            echo "Starting deployment process..."
            # CMD: ./deploy.sh <BRANCH> <TOKEN> <PROJECT_NAME> <REPO_URL>
            /tmp/deploy.sh main ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }} "${{ env.AAPANEL_PROJECT_NAME }}" "${{ github.server_url }}/${{ github.repository }}.git"
